define(["ocm_basemodel"], function(basemodel) {
  'use strict';
  var model = {
    metas: {
      potypemeta: {
        meta: {
          id: {
            type: 'string'
          }, //id
          code: {
            type: 'string',
            required: true
          }, //编码
          name: {
            type: 'string',
            required: true
          }, //名称
          saleOrgId: {
            type: 'string',
            required: true
          }, //销售组织
          saleOrgName: {
            type: 'string',
          }, //销售组织
          financeOrgId: {
            type: 'string',
            required: true
          }, //财务组织
          financeOrgName: {
            type: 'string',
          }, //财务组织
          castTypeId: {
            type: 'string',
            required: true
          }, //兑付类型
          isEnable: {
            type: 'string',
            default: '0'
          }, //是否启用
          projectId: {
            type: 'string',
            required: true
          }, //项目
          priority: {
            type: 'integer'
          }, //优先级
          isRootAccount: {
            type: 'integer'
          }, //根账户
          parentId: {
            type: 'string',
            required: true
          },
          parentCode: {
            type: 'string'
          },
          isLeaf: {
            type: "integer",
            default: '0'
          }, // 是否末级
          parentName: {
            type: 'string'
          }, //上级账户
          operation: {
            type: 'string'
          }
        },
        pageSize: 10,
      }
    },
    buttons: {
      button1: [{
        key: "add",
        label: "新增",
        iconCls: "icon-plus",
        click: "beforeEdit"
      }, {
        key: "del",
        label: "删除",
        iconCls: "icon-shanchu1",
        click: "del"
      }, {
        key: "refresh",
        label: "刷新",
        iconCls: "icon-tubiao-huangou",
        click: "refresh"
      }, {
        key: "enable",
        label: "启用",
        iconCls: "icon-qiyong",
        click: "enable"
      }, {
        key: "disable",
        label: "停用",
        iconCls: "icon-tingyong",
        click: "disable"
      }]
    },
    searchs: {
      search1: [{
        type: "text",
        key: "code",
        label: "账户编码"
      }, {
        type: "text",
        key: "name",
        label: "账户名称",
      }, {
        type: "refer",
        key: "saleOrg",
        keyfordisplay: "saleOrgName",
        label: "销售组织",
        refinfo: "organization_ocm",
        clientParam: {
          "EQ_isEnable": "1",
          "EQ_orgFuncRel": "01",
          "AUTH_refdim": "saleOrg"
        }
      }, {
        type: "refer",
        key: "financeOrg",
        label: "财务组织",
        keyfordisplay: "financeOrgName",
        refinfo: "organization_ocm",
        clientParam: {
          "EQ_isEnable": "1",
          "EQ_orgFuncRel": "07",
          "AUTH_refdim": "financeOrg"
        }
      }, {
        type: "combo",
        key: "castTypeId",
        label: "兑付类型",
        dataSource: [{
          value: "pay01",
          name: "冲抵订单"
        }, {
          value: "pay02",
          name: "货补"
        }, {
          value: "pay03",
          name: "实物货补"
        }, {
          value: "pay04",
          name: "账扣"
        }]
      }, {
        type: "radio",
        key: "isEnable",
        label: "启用状态",
        dataSource: [{
          value: '0',
          name: '未启用'
        }, {
          value: '1',
          name: '启用'
        }, {
          value: '2',
          name: '停用'
        }]
      }]
    },
    dialogs: {
      dialog1: [{
        type: "text",
        key: "code",
        label: "账户编码",
        disableInEdit: true
      }, {
        type: "text",
        key: "name",
        label: "账户名称",
      }, {
        type: "radio",
        key: "isRootAccount",
        label: "根账户",
        dataSource: [{
          value: '0',
          name: '否'
        }, {
          value: '1',
          name: '是'
        }],
        defaultvalue: '0'
      }, {
        type: "refer",
        key: "saleOrgId",
        keyfordisplay: "saleOrgName",
        label: "销售组织",
        refinfo: "organization_ocm",
        domid: "saleOrg",
        compid: "saleOrg",
        enable: false,
        clientParam: {
          "EQ_isEnable": "1",
          "EQ_orgFuncRel": "01"
        }
      }, {
        type: "refer",
        key: "financeOrgId",
        keyfordisplay: "finanOrgName",
        label: "财务组织",
        refinfo: "organization_ocm",
        enable: false,
        domid: "financeOrg",
        compid: "financeOrg",
        clientParam: {
          "EQ_isEnable": "1",
          "EQ_orgFuncRel": "07"
        }
      }, {
        type: "combo",
        key: "castTypeId",
        label: "兑付类型",
        enable: false,
        domid: "castType",
        compid: "castType",
        dataSource: [{
          value: "pay01",
          name: "冲抵订单"
        }, {
          value: "pay02",
          name: "货补"
        }, {
          value: "pay04",
          name: "账扣"
        }]
      }, {
        type: "text",
        key: "priority",
        label: "优先级",
      }, {
        type: "refer",
        key: "parentId",
        keyfordisplay: "parentName",
        label: "上级账户",
        refinfo: "fee-accounts",
        domid: "parentaccont",
        compid: "parentaccont",
        enable: true,
      }, {
        type: "label",
        key: "isEnable",
        label: "启用状态",
        defaultvalue: '0'
      }]
    },
    details: {
      detail: [{
        key: "code",
        label: "账户编码",
      }, {
        key: "name",
        label: "账户名称",
      }, {
        key: "isRootAccount",
        label: "根账户",
        computed: "rootAccountFmt"
      }, {
        key: "financeOrgName",
        label: "财务组织",
      }, {
        key: "saleOrgName",
        label: "销售组织",
      }, {
        key: "castTypeId",
        label: "兑付类型",
        computed: "castTypeFmt"
      }, {
        key: "priority",
        label: "优先级",
      }, {
        key: "parentName",
        label: "上级账户",
      }, {
        key: "isLeaf",
        label: "是否末级",
        computed: "isLeafFmt"
      }, {
        key: "isEnable",
        label: "启用状态",
        computed: "enableFmt"
      }]
    },
    grids: {
      grid1: {
        domid: "potype",
        umeta: {
          id: "grid_potype",
          data: "simpleList",
          type: "grid",
          editable: false,
          multiSelect: true,
          showNumCol: true,
        },
        columns: [{
          field: "code",
          dataType: "String",
          title: "账户编码",
          renderType: "detailRender"
        }, {
          field: "name",
          dataType: "String",
          title: "账户名称",
        }, {
          field: "saleOrgName",
          dataType: "String",
          title: "销售组织",
        }, {
          field: "financeOrgName",
          dataType: "String",
          title: "财务组织",
        }, {
          field: "castTypeId",
          dataType: "String",
          title: "兑付类型",
          renderType: "castTypeList"
        }, {
          field: "isLeaf",
          dataType: "String",
          title: "是否末级",
          renderType: "whetherRender"
        }, {
          field: "modifiedTime",
          dataType: "Date",
          title: "修改时间",
          visible: false
        }, {
          field: "isEnable",
          dataType: "String",
          title: "启用状态",
          renderType: "enableRender"
        }, {
          field: "operation",
          dataType: "String",
          title: "操作",
          renderType: "operation4single",
          fixed: true,
          width: "110px"
        }, ]
      }
    }
  };
  return new basemodel(model);
});