define(["ocm_basemodel"], function(basemodel) {
    var model = {
        metas: {
            deliveryMeta: {
                meta: {
                    id: {
                        type: "string"
                    },
                    code: {
                        type: "string",
                        required: true
                    }, //发货单号
                    pcode: {
                        type: "string"
                    }, //平台单号
                    platformId: {
                        type: "string"
                    }, //平台
                    platformName: {
                        type: "string"
                    }, //平台
                    orderCode: {
                        type: "string"
                    }, //电商单号
                    storeId: {
                        type: "string"
                    }, //店铺名称
                    storeName: {
                        type: "string"
                    }, //店铺名称
                    buyerId: {
                        type: "string"
                    }, //顾客ID
                    buyerName: {
                        type: "string"
                    }, //顾客姓名
                    contactInfo1: {
                        type: "string",
                    }, //联系方式1
                    deliveryAddress: {
                        type: "string"
                    }, //收货地址
                    deliveryReceiverProvince: {
                        type: "string"
                    }, //收货省份
                    deliveryReceiverProvinceName: {
                        type: "string"
                    }, //收货省份
                    deliveryReceiverCity: {
                        type: "string"
                    }, //收货城市
                    deliveryReceiverCityName: {
                        type: "string"
                    }, //收货城市
                    deliveryReceiverDistrict: {
                        type: "string"
                    }, //收货区县
                    deliveryReceiverDistrictName: {
                        type: "string"
                    }, //收货区县
                    deliveryReceiverTown: {
                        type: "string"
                    }, //收货乡镇
                    deliveryReceiverTownName: {
                        type: "string"
                    }, //收货乡镇
                    deliveryReceiverAddress: {
                        type: "string"
                    }, //详细地址
                    wareHouseId: {
                        type: "string",
                        required: true,
                        refmodel: JSON.stringify(refinfo["warehouse"]),
                        refcfg: '{"ctx":"/uitemplate_web"}',
                        refparam: "{}",
                        required: true
                    }, //发货仓库
                    wareHouseName: {
                        type: "string"
                    },
                    logisticsMode: {
                        type: "string"
                    }, //物流方式
                    logisticsModeId: {
                        type: "string"
                    }, //物流方式
                    serviceMode: {
                        type: "string"
                    }, //配送方式
                    billStatus: {
                        type: "string",
                        required: true
                    }, //订单状态
                    craetionTime: {
                        type: "date",
                        required: true
                    }, //单据日期
                    creationTime: {
                        type: "datetime",
                    },
                    creator: {
                        type: "string",
                    },
                    contactInfo2: {
                        type: "string",
                    }, //联系方式2  
                    isLock: {
                        type: "int",
                    }, //冻结标识
                    modifiedTime: {
                        type: "datetime",
                    },
                    modifier: {
                        type: "string",
                    },
                    lockType: {
                        type: "string",
                    }, //冻结原因
                    isSplit: {
                        type: "int",
                    }, //是否拆单发货
                    isUrgent: {
                        type: "int",
                    }, //是否加急
                    logisticsId: {
                        type: "string",
                    },
                    logisticsName: {
                        type: "string",
                    }, //快递公司名称
                    waybillNo: {
                        type: "string",
                    }, //快递编号
                    deliverTime: {
                        type: "datetime",
                    }, //发货时间
                    bookTime: {
                        type: "date",
                    }, //下单时间
                    deliveryTime: {
                        type: "date",
                    }, //要求送货时间
                    isSynch: {
                        type: "string",
                    }, //是否同步
                    billDate: {
                        type: "date"
                    },
                    // 销售组织
                    saleOrgId: {
                        type: "string",
                        required: true,
                        refmodel: JSON.stringify(refinfo["organization_ocm"]),
                        refcfg: '{"ctx":"/uitemplate_web","refName":"销售组织" }',
                        refparam: '{"EQ_isEnable":"1"}'
                    },
                    // 销售组织编码
                    saleOrgCode: {
                        type: "string"
                    },
                    // 销售组织名称
                    saleOrgName: {
                        type: "string"
                    },
                    // deliveryOrderCode: {
                    //  type: "string"
                    // }, // 发货单号
                    deliveryOperater: {
                        type: "string"
                    }, //发货安排人
                    deliveryOrderDate: {
                        type: "date"
                    }, //发货日期

                    totalDeliveryNumber: {
                        type: "numberFloat",
                        precision: 2,
                        required: true
                    }, // 总数量
                    totalAmount: {
                        type: "amountFloat"
                    }, // 总金额
                    orderStatusId: {
                        type: "string"
                    }, // 单据状态
                    orderStatusCode: {
                        type: "string"
                    },
                    orderStatusName: {
                        type: "string"
                    },
                    totalNetWeight: {
                        type: "string"
                    },
                    totalWeight: {
                        type: "string"
                    },
                    totalVolume: {
                        type: "string"
                    }
                },
                pageSize: 10
                //是否启用前端缓存
                // pageCache: true
            },
            deliveryItemsMeta: {
                meta: {
                    urmOrderCode: {
                        type: "string",
                        required: true
                    }, //零售单号
                    pcode: {
                        type: "string",
                        required: true
                    }, //外系统单号
                    shopId: {
                        type: "string",
                        required: true
                    }, //门店
                    shopName: {
                        type: "string",
                        required: true
                    }, //门店
                    pkOrgId: {
                        type: "string"
                    }, //销售组织
                    pkOrgName: {
                        type: "string"
                    }, //销售组织
                    productCode: {
                        type: "string",
                        required: true
                    }, //商品编码
                    productName: {
                        type: "string",
                        required: true
                    }, //商品名称
                    productVersionId: {
                        type: "string"
                    }, //版本号
                    deliveryNumber: {
                        type: "numberFloat",
                        required: true
                    }, //本次安排数量
                    outboundsNumber: {
                        type: "numberFloat",
                        required: true
                    }, //累计出库数量
                    expectedArrivalDate: {
                        type: "datetime"
                    }, //期望收货时间
                    isGift: {
                        type: "integer",
                        required: true
                    }, //是否赠品
                    remark: {
                        type: "string"
                    }, //备注
                    close: {
                        type: "integer",
                        required: true
                    }, //订单关闭
                },
                pageSize: 10
            },
            //拉式生成发货单开始
            referSaleOrderItemsMeta: {
                meta: {
                    retailOrderCode: {
                        type: "string"
                    }, // 零售单号
                    pcode: {
                        type: "string"
                    }, //外系统单号
                    shopId: {
                        type: 'string',
                        "refmodel": JSON.stringify(refinfo['shop']),
                        "refcfg": '{"ctx":"/uitemplate_web","refname":"门店"}',
                    }, //门店
                    shopName: {
                        type: "string"
                    }, //门店
                    pkOrgId: {
                        type: "string"
                    }, // 销售组织
                    pkOrgCode: {
                        type: "string"
                    },
                    pkOrgName: {
                        type: "string"
                    },
                    goodsId: {
                        type: "string"
                    }, // 商品编码
                    goodsVersionId: {
                        type: "string"
                    }, //商品版本号
                    skuName: {
                        type: "string"
                    }, // 商品名称
                    orderNum: {
                        type: "numberFloat"
                    }, //订货数量
                    alreadyProductDeliveryNum: {
                        type: "numberFloat"
                    }, //已安排数量
                    readyProductDeliveryNum: {
                        type: "numberFloat"
                    }, //待安排发货数量
                    stockOnHandNum: {
                        type: "numberFloat"
                    }, // 现存量
                    expectedArrivalDate: {
                        type: "date"
                    }, // 期望收货时间
                    deliveryInvOrgId: {
                        type: "string"
                    }, // 发货库存组织
                    deliveryInvOrgName: {
                        type: "string"
                    },
                    deliveryReceiverProvince: {
                        type: "string"
                    }, // 收货地址省
                    orderReceiverCity: {
                        type: "string"
                    }, // 收货地址市
                    orderReceiverDistrict: {
                        type: "string"
                    }, // 收货地址区                 
                    orderReceiverTown: {
                        type: "string"
                    }, // 收货地址镇
                    orderReceiverAddress: {
                        type: "string"
                    }, // 收货地址  .
                    orderFullReceiverAddress: {
                        type: "string"
                    }, // 收货地址全部
                    transTypeId: {
                        type: "string"
                    }, // 订单交易类型
                    transTypeName: {
                        type: "string"
                    }, // 订单交易类型
                },
                pageSize: 10
            },
            referSaleOrderItemBomsMeta: {
                meta: {
                    deliveryGoodsId: {
                        type: "string"
                    }, //发货单子表主键
                    parentGoodsName: {
                        type: "string"
                    }, //母件商品名称
                    childGoodsCode: {
                        type: "string"
                    }, //子件商品编码
                    childGoodsName: {
                        type: "string"
                    }, //子件商品名称
                    productVersionId: {
                        type: "string"
                    }, //商品版本
                    orderNumUnitName: {
                        type: "string"
                    }, //单位
                    deliveryNumber: {
                        type: "numberFloat"
                    }, //发货安排数量
                    outboundsNumber: {
                        type: "numberFloat"
                    }, //累计出库数量
                    deliveryInvOrgId: {
                        type: "string",
                        refmodel: JSON.stringify(refinfo["organization_ocm"]),
                        refcfg: '{"ctx":"/uitemplate_web","refName":"发货库存组织" }',
                        refparam: '{"EQ_orgFuncRel":"03","EQ_isEnable":"1"}',
                        required: true
                    },
                    // 发货库存组织编码")
                    deliveryInvOrgCode: {
                        type: "string"
                    },
                    // 发货库存组织名称")
                    deliveryInvOrgName: {
                        type: "string"
                    },
                    isGift: {
                        type: "numberFloat"
                    }, //赠品
                },
                pageSize: 10
            },
            deliveryItemBomsMeta: {
                meta: {
                    deliveryOrderId: {
                        type: "string"
                    }, // 销售订单主键
                    deliveryOrderItemId: {
                        type: "string"
                    }, // 销售订单商品主键
                    parentRowNum: {
                        type: "string"
                    }, // 母件商品行 行号
                    parentGoodsId: {
                        type: "string"
                    }, // 母件商品id
                    parentGoodsCode: {
                        type: "string"
                    }, // 母件商品code
                    parentGoodsName: {
                        type: "string"
                    }, // 母件商品name
                    rowNum: {
                        type: "string",
                        required: true
                    }, //行号
                    goodsId: {
                        type: "string",
                        required: true
                    }, //商品
                    goodsName: {
                        type: "string",
                        refmodel: JSON.stringify(refinfo["goods"]),
                        refcfg: '{"ctx":"/uitemplate_web"}',
                        refparam: '{"EQ_isEnable":"1"}'
                    }, //商品名称
                    goodsCode: {
                        type: "string",
                        required: true
                    }, //商品Code
                    orderNum: {
                        type: "numberFloat",
                        required: true
                    }, //本次安排数量
                    mainNum: {
                        type: "numberFloat",
                        required: true
                    }, //本次安排主数量
                    // 主数量单位
                    mainNumUnitId: {
                        type: "string"
                    },
                    // 主数量单位编码
                    mainNumUnitCode: {
                        type: "string"
                    },
                    // 主数量单位名称
                    mainNumUnitName: {
                        type: "string"
                    },
                    // 订货单位
                    orderNumUnitId: {
                        type: "string"
                    },
                    // 订货单位位编码
                    orderNumUnitCode: {
                        type: "string"
                    },
                    // 订货单位单位名称
                    orderNumUnitName: {
                        type: "string"
                    },
                    // 供应商
                    supplierId: {
                        type: "string"
                    },
                    // 供应商编码
                    supplierCode: {
                        type: "string"
                    },
                    // 供应商名称
                    supplierName: {
                        type: "string"
                    },
                    // 项目
                    projectId: {
                        type: "string"
                    },
                    // 项目编码
                    projectCode: {
                        type: "string"
                    },
                    // 项目名称
                    projectName: {
                        type: "string"
                    },
                    conversionRate: {
                        type: "float",
                        required: true
                    }, //单位换算率
                    weight: {
                        type: "float",
                        required: true
                    }, //重量
                    volume: {
                        type: "float",
                        required: true
                    }, //体积
                    basePrice: {
                        type: "priceFloat",
                        required: true
                    }, //单价
                    salePrice: {
                        type: "priceFloat",
                        required: true
                    }, //销售价格
                    amount: {
                        type: "amountFloat",
                        required: true
                    }, //原价格
                    dealPrice: {
                        type: "priceFloat",
                        required: true
                    }, //成交价
                    dealAmount: {
                        type: "amountFloat",
                        required: true
                    }, //成交金额
                    planDeliveryDate: {
                        type: "date",
                        required: true
                    }, //计划发货日期
                    deliveryInvOrgId: {
                        type: "string",
                        required: true
                    }, //发货库存组织
                    deliveryWarehouseId: {
                        type: "string",
                        required: true
                    }, //发货仓库呢
                    isClose: {
                        type: "string",
                        required: true
                    }, //是否关闭
                    remark: {
                        type: "string",
                        required: true
                    }, //备注
                    srcOrderCode: {
                        type: "string",
                        required: true
                    }, //来源订单号
                    srcOrderId: {
                        type: "string",
                        required: true
                    }, //来源订单主键
                    srcOrderItemId: {
                        type: "string",
                        required: true
                    }, //来源订单行主键
                    srcOrderItemBomId: {
                        type: "string",
                        required: true
                    }, //来源订单bom主键
                    baseGoodsOptId: {
                        type: "string",
                        required: true
                    }, //来源订单bom主键
                    version: {
                        type: "integer",
                        required: true
                    }, //版本
                    originalGoodsId: {
                        type: "string",
                        required: true
                    }, //原始版本商品
                    childGoodsQty: {
                        type: "float",
                        required: true
                    }, //包件标准用量
                    existingNum: {
                        type: "numberFloat"
                    }, //现存量
                    dr: {
                        type: "integer"
                    },

                    creator: {
                        type: "string"
                    }, //创建人
                    //创建时间
                    creationTime: {
                        type: "datetime"
                    },
                    //修改人
                    modifier: {
                        type: "string"
                    },
                    //修改时间
                    modifiedTime: {
                        type: "datetime"
                    },
                    netWeight: {
                        type: "string"
                    },
                    rowNetWeight: {
                        type: "string"
                    },
                    rowWeight: {
                        type: "string"
                    },
                    rowVolume: {
                        type: "string"
                    }
                },
                pageSize: 10
            },
            referSaleOrderSearch: {
                meta: {
                    // 销售组织
                    saleOrgId: {
                        type: "string",
                        required: true,
                        refmodel: JSON.stringify(refinfo["organization_ocm"]),
                        refcfg: '{"ctx":"/uitemplate_web","refName":"销售组织" }',
                        refparam: '{"EQ_isEnable":"1"}'
                    },
                    // 销售组织编码
                    saleOrgCode: {
                        type: "string"
                    },
                    // 销售组织名称
                    saleOrgName: {
                        type: "string"
                    },
                    deliveryOrderCode: {
                        type: "string"
                    }, // 发货单号
                    deliveryOrderDate: {
                        type: "date"
                    } //发货日期
                },
                pageSize: 10
            },
            saveCheckCreditMeta: {}
        },
        searchs: {
            search1: [{
                    type: "text",
                    key: "deliveryOrderCode",
                    label: "发货单号"
                }, {
                    type: "text",
                    key: "deliveryOrderItems--saleOrderCode",
                    label: "订单号"
                }, {
                    type: "refer",
                    key: "deliveryOrderItems--customer",
                    label: "客户",
                    refinfo: "customer",
                    refName: "客户",
                    clientParam: {
                        EQ_isEnable: "1",
                        EQ_isChannelCustomer: "1"
                    },
                    opr: "IN",
                    refcfg: {
                        ctx: "/uitemplate_web",
                        refCode: "",
                        refName: "",
                        isMultiSelectedEnabled: "true"
                    }
                },
                // {
                //   type: "refer",
                //   key: "saleOrg--id",
                //   label: "销售组织",
                //   refinfo: "organization_ocm"
                // },
                {
                    type: "daterange",
                    key: "deliveryOrderDate",
                    label: "发货日期"
                }, {
                    type: "combo",
                    key: "orderStatus",
                    label: "发货单状态",
                    url: window.pathMap.base +
                        "/cust-doc-defs/cust_doc_code?cust_doc_code=QY134",
                    namefield: "name",
                    valuefield: "code",
                    hasAll: true
                }
            ],
            search2: [{
                type: "refer",
                key: "order.shop",
                label: "门店",
                refinfo: "shopref",
                required: true
            }, {
                type: "text",
                key: "retailOrderCode",
                label: "零售单号",
            }, {
                type: "daterange",
                key: "documentDate",
                label: "零售单日期",
            }]
        },
        buttons: {
            button1: [{
                    key: "add",
                    label: "新增",
                    iconCls: "icon-plus",
                    click: "showAddRefer"
                }, {
                    key: "submit",
                    label: "提交",
                    iconCls: "icon-tubiao-shenhe",
                    // click: "submitBtn"
                    click: "submitBillBpm"
                }, {
                    key: "back",
                    label: "收回",
                    iconCls: "icon-tubiao-shenhe",
                    // click: "backBtn"
                    click: "unsubmitBillList"
                }, {
                    key: "approve",
                    label: "审批",
                    iconCls: "icon-tubiao-shenhe",
                    // click: "approve"
                    click: "approveBill"
                }, {
                    key: "unapprove",
                    label: "取消审核",
                    iconCls: "icon-tubiao-quxiaoshenhe",
                    // click: "unapprove"
                    click: "unapproveBill"
                }, {
                    key: "orderOperation",
                    label: "整单操作",
                    iconCls: "icon-plus",
                    clickArg: "$data",
                    children: [{
                        key: "openOrderBill",
                        label: "整单打开",
                        click: "openOrderBillPanel"
                    }, {
                        key: "closeOrderBil",
                        label: "整单关闭",
                        click: "closeOrderBillPanel"
                    }]
                }
                // {
                //   key: "import",
                //   label: "导入",
                //   iconCls: "icon-import",
                //   click: "importHandle"
                // },
                // {
                //   key: "export",
                //   label: "导出",
                //   iconCls: "icon-export",
                //   click: "exportHandle"
                // },
            ],
            button2: [{
                key: "cancel",
                label: "取消",
                click: "cancelBill"
            }, {
                key: "save",
                label: "保存",
                click: "saveBill",
                cls: "ui-btn-green"
            }, {
                key: "matchWarehouse",
                label: "匹配仓库",
                click: "resetdelivery",
            }],
            button3: [{
                key: "return",
                label: "返回",
                click: "retListPanel"
            }, {
                key: "edit",
                label: "编辑",
                click: "detail2bill",
                cls: "ui-btn-green delivery-edit-show"
            }, ],
            buttonDetail: [{
                key: "export",
                label: "行关闭",
                iconCls: "icon-tubiao-guanbi-xianxing",
                click: "close_row"
            }, {
                key: "export",
                label: "行打开",
                iconCls: "icon-tubiao-duigou-xianxing",
                click: "open_row"
            }]
        },
        cards: {
            card1: [{
                    type: "text",
                    key: "code",
                    label: "发货单号",
                    enable: false
                },
                //  {
                //     key: "craetionTime",
                //     type: "date",
                //     label: "单据日期",
                //     enable: false
                // },
                {
                    type: "text",
                    key: "buyerName",
                    label: "收货人"
                }, {
                    type: "text",
                    key: "contactInfo1",
                    label: "收货人电话"
                }, {
                    type: "refer",
                    key: "deliveryReceiverProvince",
                    label: "收货省",
                    refinfo: "region",
                    refName: "地区",
                    multi: false,
                    opr: 'IN'
                }, {
                    type: "refer",
                    key: "deliveryReceiverCity",
                    label: "收货市",
                    refinfo: "region",
                    refName: "地区",
                    multi: false,
                    domid: "city",
                    opr: 'IN'
                }, {
                    type: "refer",
                    key: "deliveryReceiverDistrict",
                    label: "收货区（县）",
                    refinfo: "region",
                    refName: "地区",
                    multi: false,
                    domid: "district",
                    opr: 'IN'
                }, {
                    type: "refer",
                    key: "deliveryReceiverTown",
                    label: "收货街（镇）",
                    refinfo: "region",
                    refName: "地区",
                    multi: false,
                    domid: 'town',
                    opr: 'IN'
                }, {
                    type: "text",
                    key: "orderReceiverAddress",
                    label: "收货详细地址",
                }, {
                    type: "refer",
                    key: "deliveryInvOrgId",
                    keyfordisplay: "deliveryInvOrgName",
                    label: "发货库存组织",
                    refinfo: "organization_ocm",
                    clientParam: {
                        "EQ_orgFuncRel": "03",
                        "EQ_isEnable": "1"
                    },
                    required: true
                }, {
                    type: "refer",
                    key: "wareHouseId",
                    keyfordisplay: "wareHouseName",
                    label: "发货仓库",
                    refinfo: "warehouse",
                    required: true
                }, {
                    type: "text",
                    key: "totalDeliveryNumber",
                    label: "总数量",
                    required: true,
                    enable: false
                }, {
                    type: "combo",
                    key: "billStatus",
                    label: "状态",
                    enable: false,
                    dataSource: [{
                        value: '0',
                        name: '保存'
                    }, {
                        value: '1',
                        name: '已提交'
                    }, {
                        value: '2',
                        name: '审批中'
                    }, {
                        value: '3',
                        name: '审批通过'
                    }, {
                        value: '4',
                        name: '审批不通过'
                    }, {
                        value: '5',
                        name: '全部出库'
                    }, {
                        value: '6',
                        name: '部分出库'
                    }],
                },
            ]
        },
        details: {
            detail1: [{
                key: "deliveryOrderCode",
                label: "发货单号"
            }, {
                key: "documentDate",
                type: "date",
                label: "单据日期"
            }, {
                key: "receiver",
                label: "收货人"
            }, {
                key: "receiverTel",
                label: "收货人电话"
            }, {
                key: "orderFullReceiverAddress",
                label: "收货地址"
            }, {
                key: "deliveryInvOrgName",
                label: "发货库存组织",
                // computed: "orderStatus"
            }, {
                key: "totalNetWeight",
                label: "发货仓库"
            }, {
                key: "totalDeliveryNumber",
                label: "总数量"
            }, {
                key: "billStatus",
                label: "状态",
                computed: "orderStatus"
            }, ]
        },
        grids: {
            grid1: {
                domid: "grid_deliveryOrder_dom",
                umeta: {
                    id: "grid_deliveryOrder",
                    data: "deliveryOrderList",
                    type: "grid",
                    editable: false,
                    multiSelect: true
                },
                columns: [{
                    "field": "code",
                    "dataType": "String",
                    "title": "发货单号",
                    // "renderType": "detailRender"
                }, {
                    "field": "buyerName",
                    "dataType": "String",
                    "title": "收货人"
                }, {
                    "field": "contactInfo1",
                    "dataType": "String",
                    "title": "收货人手机"
                }, {
                    "field": "deliveryAddress",
                    "dataType": "String",
                    "title": "收货人地址"
                }, {
                    "field": "totalDeliveryNumber",
                    "dataType": "String",
                    "title": "总数量"
                }, {
                    "field": "bookTime",
                    "dataType": "Date",
                    "title": "单据日期",
                    "width": "100",
                }, {
                    "field": "billStatus",
                    "dataType": "String",
                    "title": "订单状态",
                    "editOptions": {
                        "type": "combo",
                        "datasource": "orderStatusSrc"
                    },
                    "renderType": "comboRender",
                    "width": "80px",
                }, {
                    field: "creator",
                    dataType: "String",
                    title: "创建人",
                    visible: false
                }, {
                    field: "modifier",
                    dataType: "String",
                    title: "修改人",
                    visible: false
                }, {
                    field: "creationTime",
                    dataType: "Date",
                    title: "创建时间",
                    visible: false
                }, {
                    field: "modifiedTime",
                    dataType: "Date",
                    title: "修改时间",
                    visible: false
                }, {
                    field: "status",
                    dataType: "String",
                    title: "操作",
                    renderType: "operation",
                    fixed: true,
                    width: "200px"
                }]
            },
            grid2: {
                domid: "grid_delivery_item_eidt_dom",
                umeta: {
                    id: "grid_delivery_item_edit",
                    data: "deliveryOrderItemsList",
                    type: "grid",
                    editable: true,
                    showNumCol: true,
                    onBeforeEditFun: "beforeEditCheck"
                },
                columns: [{
                    "field": "urmOrderCode",
                    "dataType": "String",
                    "title": "零售单号",
                    "editable": false,
                    "required": true,
                }, {
                    "field": "pcode",
                    "dataType": "String",
                    "title": "外系统单号",
                    "editable": false,
                    "required": true,
                }, {
                    "field": "shopName",
                    "dataType": "String",
                    "title": "门店",
                    "editable": false,
                    "required": true,
                }, {
                    "field": "pkOrgName",
                    "dataType": "String",
                    "title": "销售组织"
                }, {
                    "field": "productCode",
                    "dataType": "String",
                    "title": "商品编码"
                }, {
                    "field": "productName",
                    "dataType": "String",
                    "title": "商品名称",
                    "editable": false,
                    "required": true,
                }, {
                    "field": "productVersionId",
                    "dataType": "String",
                    "title": "版本号",
                    "editable": false,
                    // "required": true,
                }, {
                    "field": "deliveryNumber",
                    "dataType": "String",
                    "title": "本次安排数量",
                    "required": true,
                }, {
                    "field": "outboundsNumber",
                    "dataType": "String",
                    "title": "累计出库数量",
                    "editable": false,
                    "required": true,
                }, {
                    "field": "expectedArrivalDate",
                    "dataType": "Datetime",
                    "title": "期望收货时间",
                    "editable": false,
                }, {
                    "field": "isGift",
                    "dataType": "String",
                    "title": "是否赠品",
                    "editOptions": {
                        "type": "combo",
                        "datasource": "isGiftSrc"
                    },
                    "renderType": "comboRender",
                    "editable": false,
                    "required": true,
                }, {
                    "field": "remark",
                    "dataType": "String",
                    "title": "备注",
                }, {
                    "field": "close",
                    "dataType": "String",
                    "title": "订单关闭",
                    "editOptions": {
                        "type": "combo",
                        "datasource": "isGiftSrc"
                    },
                    "renderType": "comboRender",
                    "editable": false,
                    "required": true,
                }, ]
            },
            grid3: {
                domid: "grid_delivery_item_detail_dom",
                umeta: {
                    id: "grid_delivery_item_detail",
                    data: "deliveryOrderItemsList",
                    type: "grid",
                    editable: false,
                    showNumCol: true,
                    multiSelect: true
                },
                columns: [{
                        field: "saleOrderCode",
                        dataType: "String",
                        title: "订单编号"
                    }, {
                        field: "customerName",
                        dataType: "String",
                        title: "客户"
                    }, {
                        field: "goodsCode",
                        dataType: "String",
                        title: "商品编码"
                    }, {
                        field: "goodsName",
                        dataType: "String",
                        title: "商品名称"
                    }, {
                        field: "baseGoodsOptValue",
                        dataType: "String",
                        title: "商品选配",
                        renderType: "goodsOptDetails"
                    },

                    {
                        field: "batchCodeName",
                        dataType: "String",
                        title: "批号"
                    }, {
                        field: "supplierName",
                        dataType: "String",
                        title: "供应商",
                        visible: false
                    }, {
                        field: "logisticsName",
                        dataType: "String",
                        title: "承运商",
                    }, {
                        field: "projectName",
                        dataType: "String",
                        title: "项目",
                        visible: false
                    }, {
                        field: "orderNum",
                        dataType: "String",
                        title: "本次安排数量",
                        required: true
                    }, {
                        field: "mainNum",
                        dataType: "String",
                        title: "本次安排主数量",
                    }, {
                        field: "mainNumUnitName",
                        dataType: "String",
                        title: "单位",
                        visible: false
                    }, {
                        field: "mainNumUnitName",
                        dataType: "String",
                        title: "主数量单位",
                        visible: false
                    }, {
                        field: "dealPrice",
                        dataType: "String",
                        title: "成交价",
                        visible: false
                    }, {
                        field: "supplierPrice",
                        dataType: "String",
                        title: "上级原价",
                        visible: false
                    }, {
                        field: "weight",
                        dataType: "Float",
                        title: "重量",
                        visible: false
                    }, {
                        field: "netWeight",
                        dataType: "Float",
                        title: "净重",
                        visible: false
                    }, {
                        field: "volume",
                        dataType: "Float",
                        title: "体积",
                        visible: false
                    }, {
                        field: "dealAmount",
                        dataType: "String",
                        title: "金额"
                    }, {
                        field: "planDeliveryDate",
                        dataType: "Date",
                        title: "计划发货日期"
                    }, {
                        field: "deliveryInvOrgName",
                        dataType: "String",
                        title: "发货库存组织"
                    }, {
                        field: "settleFinancialOrgName",
                        dataType: "String",
                        title: "结算财务组织 "
                    }, {
                        field: "deliveryWarehouseName",
                        dataType: "String",
                        title: "发货仓库"
                    }, {
                        field: "receiverAddress",
                        dataType: "String",
                        title: "收货地址"
                    }, {
                        field: "receiver",
                        dataType: "String",
                        title: "收货联系人"
                    }, {
                        field: "receiverPhone",
                        dataType: "String",
                        title: "收货联系电话"
                    }, {
                        field: "remark",
                        dataType: "String",
                        title: "备注"
                    }, {
                        field: "goodsSupplement",
                        dataType: "checkbox",
                        title: "货补",
                        renderType: "disableBooleanRender",
                    }, {
                        field: "isGift",
                        dataType: "checkbox",
                        title: "赠品",
                        renderType: "disableBooleanRender"
                    }, {
                        field: "isClose",
                        dataType: "checkbox",
                        title: "关闭",
                        renderType: "disableBooleanRender"
                    }, {
                        field: "stockOutNum",
                        dataType: "String",
                        title: "累计出库数量"
                    }, {
                        field: "signNum",
                        dataType: "String",
                        title: "累计签收数量"
                    }, {
                        field: "version",
                        dataType: "integer",
                        title: "版本号",
                        editable: false
                    }
                ]
            },
            grid4: {
                domid: "grid_refer_item_dom",
                umeta: {
                    id: "grid_refer_item",
                    data: "referSaleOrderItemsList",
                    type: "grid",
                    editable: false,
                    multiSelect: true,
                    showNumCol: true,
                    onRowSelected: "referSelectItemHandle",
                    onRowUnSelected: "referUnSelectItemHandle"
                },
                columns: [{
                    field: "retailOrderCode",
                    dataType: "String",
                    width: "160px",
                    title: "零售单号"
                }, {
                    field: "pcode",
                    dataType: "String",
                    title: "外系统单号"
                }, {
                    field: "shopName",
                    dataType: "String",
                    title: "门店"
                }, {
                    field: "pkOrgName",
                    dataType: "String",
                    title: "销售组织"
                }, {
                    field: "receiver",
                    dataType: "String",
                    title: "收货人",
                }, {
                    field: "receiverTel",
                    dataType: "String",
                    title: "收货人电话",
                }, {
                    field: "orderFullReceiverAddress",
                    dataType: "String",
                    title: "收货人地址",
                }, {
                    field: "goodsId",
                    dataType: "String",
                    title: "商品编码",
                }, {
                    field: "skuName",
                    dataType: "String",
                    title: "商品名称",
                }, {
                    field: "goodsVersionId",
                    dataType: "String",
                    title: "商品版本号",
                }, {
                    field: "orderNum",
                    dataType: "String",
                    title: "订货数量"
                }, {
                    field: "alreadyProductDeliveryNum",
                    dataType: "String",
                    title: "已安排数量",
                }, {
                    field: "readyProductDeliveryNum",
                    dataType: "String",
                    title: "待安排发货数量"
                }, {
                    field: "stockOnHandNum",
                    dataType: "String",
                    title: "现存量"
                }, {
                    field: "deliveryTime",
                    dataType: "Date",
                    title: "期望收货时间"
                }, {
                    field: "deliveryInvOrgName",
                    dataType: "String",
                    title: "发货库存组织"
                }, {
                    field: "transTypeName",
                    dataType: "String",
                    title: "订单交易类型"
                }, {
                    field: "remark",
                    dataType: "String",
                    title: "备注",
                }]
            },
            grid5: {
                domid: "grid_referListItem_saleorder_dom",
                umeta: {
                    id: "grid_referListItem_saleorder",
                    data: "selectedreferListItems",
                    type: "grid",
                    editable: true,
                    showNumCol: true,
                    onBeforeEditFun: "beforeEditCheck2"
                },
                columns: [{
                    field: "retailOrderCode",
                    dataType: "String",
                    width: "160px",
                    title: "零售单号"
                }, {
                    field: "pcode",
                    dataType: "String",
                    title: "外系统单号"
                }, {
                    field: "shopName",
                    dataType: "String",
                    title: "门店"
                }, {
                    field: "pkOrgName",
                    dataType: "String",
                    title: "销售组织"
                }, {
                    field: "receiver",
                    dataType: "String",
                    title: "收货人",
                }, {
                    field: "receiverTel",
                    dataType: "String",
                    title: "收货人电话",
                }, {
                    field: "orderFullReceiverAddress",
                    dataType: "String",
                    title: "收货人地址",
                }, {
                    field: "goodsId",
                    dataType: "String",
                    title: "商品编码",
                }, {
                    field: "skuName",
                    dataType: "String",
                    title: "商品名称",
                }, {
                    field: "goodsVersionId",
                    dataType: "String",
                    title: "商品版本号",
                }, {
                    field: "orderNum",
                    dataType: "String",
                    title: "订货数量"
                }, {
                    field: "alreadyProductDeliveryNum",
                    dataType: "String",
                    title: "已安排数量",
                }, {
                    field: "readyProductDeliveryNum",
                    dataType: "String",
                    title: "待安排发货数量"
                }, {
                    field: "stockOnHandNum",
                    dataType: "String",
                    title: "现存量"
                }, {
                    field: "deliveryTime",
                    dataType: "Date",
                    title: "期望收货时间"
                }, {
                    field: "deliveryInvOrgName",
                    dataType: "String",
                    title: "发货库存组织"
                }, {
                    field: "transTypeName",
                    dataType: "String",
                    title: "订单交易类型"
                }, {
                    field: "remark",
                    dataType: "String",
                    title: "备注",
                }]
            },
            grid6: {
                domid: "",
                umeta: {
                    id: "grid_refer_item_bom",
                    data: "referSaleOrderItemBomsList",
                    type: "grid",
                    editable: false,
                    showNumCol: true
                },
                columns: [{
                    field: "rowNum",
                    dataType: "String",
                    title: "行号"
                }, {
                    field: "parentGoodsName",
                    dataType: "String",
                    title: "母件商品名称",
                    editable: false
                }, {
                    field: "goodsCode",
                    dataType: "String",
                    title: "商品编码"
                }, {
                    field: "goodsName",
                    dataType: "String",
                    title: "商品名称"
                }, {
                    field: "orderNum",
                    dataType: "String",
                    title: "订货数量",
                    required: true
                }, {
                    field: "mainNum",
                    dataType: "String",
                    title: "主数量"
                }, {
                    field: "mainNumUnitName",
                    dataType: "String",
                    title: "主数量单位"
                }, {
                    field: "childGoodsQty",
                    dataType: "String",
                    title: "标准用量"
                }, {
                    field: "dealPrice",
                    dataType: "String",
                    title: "单价",
                    required: true
                }, {
                    field: "dealAmount",
                    dataType: "String",
                    title: "金额"
                }, {
                    field: "isClose",
                    dataType: "checkbox",
                    title: "关闭",
                    width: "130px",
                    renderType: "disableBooleanRender",
                    editable: false
                }, {
                    field: "goodsSupplement",
                    dataType: "checkbox",
                    title: "货补",
                    editable: false,
                    visible: false,
                    renderType: "disableBooleanRender",
                }, {
                    field: "isGift",
                    dataType: "checkbox",
                    title: "赠品",
                    editType: "float",
                    renderType: "disableBooleanRender",
                    editable: false
                }, {
                    field: "version",
                    dataType: "integer",
                    title: "版本号",
                    editable: false
                }, {
                    field: "creator",
                    dataType: "String",
                    title: "创建人",
                    editable: false,
                    visible: false
                }, {
                    field: "creationTime",
                    dataType: "Date",
                    title: "创建时间",
                    editable: false,
                    visible: false
                }, {
                    field: "modifier",
                    dataType: "String",
                    title: "修改人",
                    editable: false,
                    visible: false
                }, {
                    field: "modifiedTime",
                    dataType: "Date",
                    title: "修改时间",
                    editable: false,
                    visible: false
                }]
            },
            grid7: {
                domid: "",
                umeta: {
                    id: "grid_referListItem_bom_saleorder",
                    data: "selectedreferListItemBoms",
                    type: "grid",
                    editable: false,
                    showNumCol: true
                },
                columns: [{
                    field: "rowNum",
                    dataType: "String",
                    title: "行号"
                }, {
                    field: "parentGoodsName",
                    dataType: "String",
                    title: "母件商品名称",
                    editable: false
                }, {
                    field: "goodsCode",
                    dataType: "String",
                    title: "商品编码"
                }, {
                    field: "goodsName",
                    dataType: "String",
                    title: "商品名称"
                }, {
                    field: "orderNum",
                    dataType: "String",
                    title: "订货数量",
                    required: true
                }, {
                    field: "mainNum",
                    dataType: "String",
                    title: "主数量"
                }, {
                    field: "mainNumUnitName",
                    dataType: "String",
                    title: "主数量单位"
                }, {
                    field: "childGoodsQty",
                    dataType: "String",
                    title: "标准用量"
                }, {
                    field: "existingNum",
                    dataType: "String",
                    title: "现存量"
                }, {
                    field: "dealPrice",
                    dataType: "String",
                    title: "单价",
                    required: true
                }, {
                    field: "dealAmount",
                    dataType: "String",
                    title: "金额"
                }, {
                    field: "isClose",
                    dataType: "checkbox",
                    title: "关闭",
                    width: "130px",
                    renderType: "disableBooleanRender",
                    editable: false
                }, {
                    field: "goodsSupplement",
                    dataType: "checkbox",
                    title: "货补",
                    editable: false,
                    visible: false,
                    renderType: "disableBooleanRender",
                }, {
                    field: "isGift",
                    dataType: "checkbox",
                    title: "赠品",
                    editType: "float",
                    renderType: "disableBooleanRender",
                    editable: false
                }, {
                    field: "version",
                    dataType: "integer",
                    title: "版本号",
                    editable: false
                }, {
                    field: "creator",
                    dataType: "String",
                    title: "创建人",
                    editable: false,
                    visible: false
                }, {
                    field: "creationTime",
                    dataType: "Date",
                    title: "创建时间",
                    editable: false,
                    visible: false
                }, {
                    field: "modifier",
                    dataType: "String",
                    title: "修改人",
                    editable: false,
                    visible: false
                }, {
                    field: "modifiedTime",
                    dataType: "Date",
                    title: "修改时间",
                    editable: false,
                    visible: false
                }]
            },
            grid8: {
                domid: "grid_delivery_item_bom_detail_dom",
                umeta: {
                    id: "grid_delivery_item-bom_detail",
                    data: "deliveryOrderItemBomsList",
                    type: "grid",
                    editable: false,
                    showNumCol: true
                },
                columns: [{
                    field: "rowNum",
                    dataType: "String",
                    title: "行号"
                }, {
                    field: "parentGoodsName",
                    dataType: "String",
                    title: "母件商品名称",
                    editable: false
                }, {
                    field: "goodsCode",
                    dataType: "String",
                    title: "商品编码"
                }, {
                    field: "goodsName",
                    dataType: "String",
                    title: "商品名称"
                }, {
                    field: "baseGoodsOptValue",
                    dataType: "String",
                    title: "商品选配"
                }, {
                    field: "orderNum",
                    dataType: "Stringfloat",
                    title: "订货数量",
                    required: true
                }, {
                    field: "mainNum",
                    dataType: "String",
                    title: "主数量"
                }, {
                    field: "mainNumUnitName",
                    dataType: "String",
                    title: "主数量单位"
                }, {
                    field: "childGoodsQty",
                    dataType: "String",
                    title: "标准用量"
                }, {
                    field: "dealPrice",
                    dataType: "String",
                    title: "单价",
                    required: true
                }, {
                    field: "dealAmount",
                    dataType: "String",
                    title: "金额"
                }, {
                    field: "isClose",
                    dataType: "checkbox",
                    title: "关闭",
                    width: "130px",
                    renderType: "disableBooleanRender",
                    editable: false
                }, {
                    field: "goodsSupplement",
                    dataType: "checkbox",
                    title: "货补",
                    editable: false,
                    renderType: "disableBooleanRender",
                }, {
                    field: "isGift",
                    dataType: "checkbox",
                    title: "赠品",
                    editType: "float",
                    renderType: "disableBooleanRender",
                    editable: false
                }, {
                    field: "version",
                    dataType: "integer",
                    title: "版本号",
                    editable: false
                }, {
                    field: "creator",
                    dataType: "String",
                    title: "创建人",
                    editable: false,
                    visible: false
                }, {
                    field: "creationTime",
                    dataType: "Date",
                    title: "创建时间",
                    editable: false,
                    visible: false
                }, {
                    field: "modifier",
                    dataType: "String",
                    title: "修改人",
                    editable: false,
                    visible: false
                }, {
                    field: "modifiedTime",
                    dataType: "Date",
                    title: "修改时间",
                    editable: false,
                    visible: false
                }]
            },
            grid9: {
                domid: "grid_delivery_item_bom_edit_dom",
                umeta: {
                    id: "grid_delivery_item-bom_edit",
                    data: "deliveryOrderItemBomsList",
                    type: "grid",
                    editable: false,
                    showNumCol: true
                },
                columns: [
                    /* {
                      field: "rowNum",
                      dataType: "String",
                      title: "行号"
                    }, */
                    {
                        field: "parentGoodsName",
                        dataType: "String",
                        title: "母件商品名称",
                        editable: false
                    }, {
                        field: "goodsCode",
                        dataType: "String",
                        title: "商品编码",
                        editable: false
                    }, {
                        field: "goodsName",
                        dataType: "String",
                        title: "商品名称",
                        editable: false
                    }, {
                        field: "baseGoodsOptValue",
                        dataType: "String",
                        title: "商品选配"
                    }, {
                        field: "orderNum",
                        dataType: "String",
                        title: "订货数量",
                        required: true
                    }, {
                        field: "mainNum",
                        dataType: "String",
                        title: "主数量",
                        editable: false
                    }, {
                        field: "mainNumUnitName",
                        dataType: "String",
                        title: "主数量单位"
                    }, {
                        field: "childGoodsQty",
                        dataType: "String",
                        title: "标准用量",
                        editable: false
                    }, {
                        field: "dealPrice",
                        dataType: "String",
                        title: "单价",
                        required: true,
                        editable: false
                    }, {
                        field: "dealAmount",
                        dataType: "String",
                        title: "金额",
                        editable: false
                    }, {
                        field: "isClose",
                        dataType: "checkbox",
                        title: "关闭",
                        width: "130px",
                        renderType: "disableBooleanRender",
                        editable: false
                    }, {
                        field: "goodsSupplement",
                        dataType: "checkbox",
                        title: "货补",
                        editable: false,
                        renderType: "disableBooleanRender",
                    }, {
                        field: "isGift",
                        dataType: "checkbox",
                        title: "赠品",
                        editType: "float",
                        renderType: "disableBooleanRender",
                        editable: false
                    }, {
                        field: "version",
                        dataType: "integer",
                        title: "版本号",
                        editable: false
                    }, {
                        field: "creator",
                        dataType: "String",
                        title: "创建人",
                        editable: false,
                        visible: false
                    }, {
                        field: "creationTime",
                        dataType: "Date",
                        title: "创建时间",
                        editable: false,
                        visible: false
                    }, {
                        field: "modifier",
                        dataType: "String",
                        title: "修改人",
                        editable: false,
                        visible: false
                    }, {
                        field: "modifiedTime",
                        dataType: "Date",
                        title: "修改时间",
                        editable: false,
                        visible: false
                    }
                ]
            },
            saveCheckCreditDetail: {
                domid: "saveCheckCreditDetail",
                umeta: {
                    id: "check_credit_detail",
                    data: "saveCheckCreditDetailItems",
                    type: "grid",
                    editable: false
                },
                columns: [{
                    field: "ctreditCtrlStrategyName",
                    dataType: "String",
                    title: "控制策略"
                }, {
                    field: "organizationName",
                    dataType: "String",
                    title: "财务组织"
                }, {
                    field: "saleOrgName",
                    dataType: "String",
                    title: "销售组织"
                }, {
                    field: "trantypeName",
                    dataType: "String",
                    title: "订单类型"
                }, {
                    field: "customerName",
                    dataType: "String",
                    title: "客户"
                }, {
                    field: "occupyOrderStatus",
                    dataType: "String",
                    title: "信用占用开始时点"
                }, {
                    field: "creditCtrlType",
                    dataType: "String",
                    title: "控制方式",
                    dataSource: [{
                        value: "01",
                        name: "提示"
                    }, {
                        value: "02",
                        name: "严格控制"
                    }]
                }, {
                    field: "creditLimit",
                    dataType: "String",
                    title: "信用额度"
                }, {
                    field: "occupyLimit",
                    dataType: "String",
                    title: "信用占用"
                }, {
                    field: "creditBeyondMoney",
                    dataType: "String",
                    title: "超信用金额"
                }, ]
            },
        }
    };
    return new basemodel(model);
});